apiVersion: v1
kind: Service
metadata:
  name: virtual-zoo-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.ioio/port: "9113"
spec:
  type: LoadBalancer
  selector:
    app: virtual-zoo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
